// Yoga asanas and pranayama (built in, never stored). Logged as rounds × hold (asanas), rounds and time (Surya
// Namaskar), or time (pranayama). MET values from the Compendium of Physical Activities (2024): Hatha 2.5,
// Surya Namaskar 3.3, Nadisodhana 2.0, sitting quietly / meditating 1.3. Kapalbhati and Bhastrika have no entry of
// their own; they're counted like Nadisodhana.
import type { Exercise, YogaLog } from './model';

type Pose = [id: string, name: string, log: YogaLog, met: number, setup: string[], exec: string[], avoid: string[], art?: false];
const SIDE = 'Hold, then do the other side: log each side as a round.';

const ASANAS: Pose[] = [
  ['surya-namaskar', 'Surya Namaskar (Sun salutation)', 'rounds', 3.3,
    ['Stand at the front of the mat, feet together, palms joined at the chest.'],
    ['Flow through the 12 positions: raise arms, fold forward, step back to lunge, plank, lower (eight limbs), cobra, downward dog, lunge, fold, rise, return.', 'Inhale as you open or lift, exhale as you fold or lower.', 'One round = both sides (right leg leads, then left).'],
    ['Rushing and losing the breath.', 'Dropping the hips or collapsing the lower back in plank and cobra.']],
  ['tadasana', 'Tadasana (Mountain pose)', 'hold', 2.5,
    ['Feet together or hip-width, weight even across both feet.'],
    ['Lengthen up through the crown; shoulders relaxed down.', 'Optionally raise the arms overhead, palms facing, and stretch up (Urdhva Hastasana).', 'Breathe slowly through the nose.'],
    ['Locking the knees.', 'Pushing the ribs forward and arching the lower back.']],
  ['vrksasana', 'Vrksasana (Tree pose)', 'hold', 2.5,
    ['Stand in Tadasana; shift weight onto the left foot.'],
    ['Place the right sole on the inner calf or inner thigh, knee opening out.', 'Palms together at the chest or overhead; fix the gaze on a still point.', SIDE],
    ['Pressing the foot into the side of the knee.', 'Letting the standing hip jut out to the side.'], false],
  ['utkatasana', 'Utkatasana (Chair pose)', 'hold', 2.5,
    ['Feet together or hip-width; arms reaching up alongside the ears.'],
    ['Bend the knees and sit the hips back as if onto a chair.', 'Weight in the heels; chest lifted.', 'Hold, then straighten on an inhale.'],
    ['Knees drifting far past the toes or inward.', 'Rounding the back.'], false],
  ['trikonasana', 'Trikonasana (Triangle pose)', 'hold', 2.5,
    ['Step the feet about a leg-length apart; right foot turned out, left slightly in.'],
    ['Arms out at shoulder height; reach forward over the right leg, then lower the right hand to the shin or a block.', 'Left arm straight up; look up or ahead.', SIDE],
    ['Collapsing the side of the waist toward the floor.', 'Hyperextending the front knee.'], false],
  ['virabhadrasana-1', 'Virabhadrasana I (Warrior I)', 'hold', 2.5,
    ['From standing, step the left foot back about a metre; turn it out slightly, heel down.'],
    ['Bend the front knee over the ankle; hips square to the front.', 'Raise the arms overhead.', SIDE],
    ['Front knee caving in.', 'Arching hard through the lower back.'], false],
  ['virabhadrasana-2', 'Virabhadrasana II (Warrior II)', 'hold', 2.5,
    ['Wide stance; front foot pointing forward, back foot parallel to the short edge of the mat.'],
    ['Bend the front knee over the ankle; arms out at shoulder height.', 'Gaze over the front fingers; torso upright over the hips.', SIDE],
    ['Leaning the torso over the front leg.', 'Front knee rolling inward.'], false],
  ['uttanasana', 'Uttanasana (Standing forward bend)', 'hold', 2.5,
    ['Stand with feet hip-width.'],
    ['Exhale and fold forward from the hips, not the waist.', 'Let the head hang; hands to the shins, floor or opposite elbows.', 'Bend the knees as much as you need.'],
    ['Rounding hard from the lower back with locked knees.', 'Coming up quickly (dizziness): rise slowly.']],
  ['ardha-chakrasana', 'Ardha Chakrasana (Standing backbend)', 'hold', 2.5,
    ['Stand with feet together; hands on the lower back, fingers pointing down.'],
    ['Inhale, lift the chest and gently bend backward, hips pressing forward.', 'Keep the neck long.', 'Hold a few breaths, then come up.'],
    ['Dropping the head back sharply.', 'Doing it with lower-back pain.'], false],
  ['kati-chakrasana', 'Kati Chakrasana (Standing spinal twist)', 'rounds', 2.5,
    ['Stand with feet shoulder-width, arms relaxed.'],
    ['Twist to the right from the waist, letting the arms swing and wrap round the body.', 'Return to centre and twist left: that is one round.', 'Keep the hips facing forward.'],
    ['Twisting from the knees.', 'Jerking into the twist.'], false],
  ['malasana', 'Malasana (Garland pose)', 'hold', 2.5,
    ['Feet a little wider than the hips, toes turned out.'],
    ['Squat down with the heels on the floor (or on a folded mat).', 'Palms together; elbows press the knees open.', 'Lift the chest.'],
    ['Forcing heels down if the knees hurt.'], false],
  ['anjaneyasana', 'Anjaneyasana (Low lunge)', 'hold', 2.5,
    ['From downward dog step the right foot forward between the hands; lower the left knee to the mat.'],
    ['Sink the hips forward and down until you feel the front of the left hip stretch.', 'Lift the chest; hands on the front thigh or overhead.', SIDE],
    ['Front knee far past the ankle.', 'Knee pressing on a hard floor: pad it.']],
  ['adho-mukha-svanasana', 'Adho Mukha Svanasana (Downward dog)', 'hold', 2.5,
    ['Start on hands and knees, hands shoulder-width, fingers spread.'],
    ['Tuck the toes and lift the hips up and back into an upside-down V.', 'Press the floor away; heels reach toward the mat (knees may bend).', 'Head between the arms, neck relaxed.'],
    ['Rounding the back to force the heels down.', 'Shoulders shrugged to the ears.']],
  ['phalakasana', 'Phalakasana (Plank pose)', 'hold', 2.5,
    ['Hands under the shoulders, legs straight back, toes tucked.'],
    ['Body in one line from head to heels.', 'Brace the belly; push the floor away.', 'Breathe steadily.'],
    ['Hips sagging or piking up.', 'Holding the breath.']],
  ['vasisthasana', 'Vasisthasana (Side plank)', 'hold', 2.5,
    ['From plank, roll onto the outer edge of the right foot, left foot stacked on top.'],
    ['Right hand (or forearm) under the shoulder; lift the hips.', 'Left arm up to the ceiling.', SIDE],
    ['Hips dropping toward the floor.']],
  ['ashtanga-namaskara', 'Ashtanga Namaskara (Eight-limbed pose)', 'hold', 2.5,
    ['From plank, lower the knees to the mat.'],
    ['Lower the chest and chin between the hands, hips raised.', 'Toes, knees, chest, chin and both hands touch the mat.', 'Part of Surya Namaskar; hold briefly on its own.'],
    ['Letting the elbows flare wide.']],
  ['bhujangasana', 'Bhujangasana (Cobra pose)', 'hold', 2.5,
    ['Lie on the front, legs together, tops of the feet down; hands under the shoulders.'],
    ['Inhale and lift the chest using the back, elbows bent and close to the body.', 'Hips and legs stay on the mat.', 'Lower on an exhale.'],
    ['Pushing up on straight arms and crunching the lower back.', 'Shrugging the shoulders.'], false],
  ['salabhasana', 'Salabhasana (Locust pose)', 'hold', 2.5,
    ['Lie on the front, arms by the sides or reaching forward, forehead down.'],
    ['Inhale and lift the chest, arms and legs off the mat.', 'Keep the neck long, gaze down.', 'Lower on an exhale.'],
    ['Throwing the head back.', 'Bending the knees to lift higher.']],
  ['dhanurasana', 'Dhanurasana (Bow pose)', 'hold', 2.5,
    ['Lie on the front; bend the knees and hold the outer ankles.'],
    ['Inhale and kick the feet into the hands, lifting the chest and thighs.', 'Balance on the belly; breathe.', 'Release slowly.'],
    ['Doing it with a back or neck injury.', 'Knees splaying very wide.'], false],
  ['makarasana', 'Makarasana (Crocodile pose)', 'hold', 1.3,
    ['Lie on the front; fold the arms and rest the forehead on them.'],
    ['Legs apart, heels in or out, whatever is comfortable.', 'Let the belly soften against the mat and breathe slowly.', 'A resting pose between back bends.'],
    ['Turning the head to one side for long.'], false],
  ['marjaryasana-bitilasana', 'Marjaryasana–Bitilasana (Cat–cow)', 'hold', 2.5,
    ['Hands under the shoulders, knees under the hips.'],
    ['Inhale: drop the belly, lift the chest and tailbone (cow).', 'Exhale: round the back, tuck the chin (cat).', 'Move with the breath; log the minutes you flowed.'],
    ['Moving from the neck only.', 'Rushing the breath.']],
  ['balasana', 'Balasana (Child’s pose)', 'hold', 1.3,
    ['Kneel, big toes together, knees together or apart.'],
    ['Sit the hips back to the heels and fold forward.', 'Forehead to the mat; arms forward or alongside the body.', 'Breathe into the back.'],
    ['Forcing the hips down with sore knees: put a cushion between.']],
  ['ustrasana', 'Ustrasana (Camel pose)', 'hold', 2.5,
    ['Kneel with knees hip-width, thighs upright; hands on the lower back.'],
    ['Lift the chest and lean back, hips over the knees.', 'Reach the hands to the heels if you can.', 'Come up slowly, chest leading.'],
    ['Letting the hips move behind the knees.', 'Dropping the head back hard.'], false],
  ['vajrasana', 'Vajrasana (Thunderbolt pose)', 'hold', 1.3,
    ['Kneel and sit back on the heels, big toes touching.'],
    ['Spine tall, hands on the thighs.', 'Breathe slowly; traditionally done after meals.'],
    ['Staying if the knees or ankles hurt: sit on a cushion.'], false],
  ['sukhasana', 'Sukhasana (Easy pose)', 'hold', 1.3,
    ['Sit cross-legged on the mat or a folded blanket.'],
    ['Spine tall, shoulders soft, hands on the knees.', 'Used for breathing and meditation.'],
    ['Slumping: sit on a cushion so the hips are above the knees.'], false],
  ['padmasana', 'Padmasana (Lotus pose)', 'hold', 1.3,
    ['Sit with legs out. Place the right foot on the left thigh, then the left foot on the right thigh.'],
    ['Spine tall, hands on the knees.', 'Change which leg is on top next time.'],
    ['Forcing it: lotus needs open hips. Knee pain means stop.'], false],
  ['baddha-konasana', 'Baddha Konasana (Butterfly pose)', 'hold', 2.5,
    ['Sit and bring the soles of the feet together, heels toward you.'],
    ['Hold the feet; let the knees fall open.', 'Lengthen the spine, then fold forward a little if it’s comfortable.'],
    ['Pushing the knees down with the hands.']],
  ['paschimottanasana', 'Paschimottanasana (Seated forward bend)', 'hold', 2.5,
    ['Sit with legs straight out, feet flexed.'],
    ['Inhale to lengthen; exhale and fold forward from the hips.', 'Hold the shins, ankles or feet.', 'Soften the knees if the hamstrings are tight.'],
    ['Rounding hard from the upper back to reach the toes.']],
  ['janu-sirsasana', 'Janu Sirsasana (Head-to-knee pose)', 'hold', 2.5,
    ['Sit with the left leg straight; bend the right knee, sole against the inner left thigh.'],
    ['Turn slightly toward the straight leg and fold over it.', 'Hold the shin or foot.', SIDE],
    ['Forcing the head to the knee.'], false],
  ['ardha-matsyendrasana', 'Ardha Matsyendrasana (Half spinal twist)', 'hold', 2.5,
    ['Sit tall; bend the right knee and step the right foot outside the left knee.'],
    ['Right hand behind you; hug the knee with the left arm (or hook the elbow outside it).', 'Inhale to lengthen, exhale to twist to the right.', SIDE],
    ['Twisting by pulling hard with the arms.', 'Slumping the spine.'], false],
  ['gomukhasana', 'Gomukhasana (Cow face pose)', 'hold', 2.5,
    ['Sit; stack the right knee over the left, feet beside the hips.'],
    ['Reach the left arm up and bend it behind the head; the right arm behind the back; clasp the fingers (or hold a strap).', SIDE],
    ['Arching the lower back to reach the hands.'], false],
  ['navasana', 'Navasana (Boat pose)', 'hold', 2.5,
    ['Sit with knees bent, feet on the floor, hands behind the thighs.'],
    ['Lean back a little and lift the feet, shins parallel to the floor.', 'Straighten the legs and reach the arms forward if you can.', 'Chest lifted, spine long.'],
    ['Rounding the back and collapsing the chest.']],
  ['setu-bandhasana', 'Setu Bandhasana (Bridge pose)', 'hold', 2.5,
    ['Lie on the back, knees bent, feet hip-width near the hips; arms by the sides.'],
    ['Press through the feet and lift the hips.', 'Roll the shoulders under; clasp the hands beneath you if you like.', 'Lower slowly, one vertebra at a time.'],
    ['Knees falling apart.', 'Turning the head while up.']],
  ['pavanmuktasana', 'Pavanmuktasana (Wind-relieving pose)', 'hold', 2.5,
    ['Lie on the back, legs straight.'],
    ['Bend both knees and hug them to the chest (or one leg at a time).', 'Optionally lift the head toward the knees.', 'Breathe into the belly; rock gently side to side.'],
    ['Straining the neck to reach the knees.']],
  ['supta-matsyendrasana', 'Supta Matsyendrasana (Lying twist)', 'hold', 1.3,
    ['Lie on the back; hug the right knee in.'],
    ['Let the right knee fall across the body to the left; right arm out to the side.', 'Look to the right if the neck is happy.', SIDE],
    ['Forcing the knee to the floor.'], false],
  ['sarvangasana', 'Sarvangasana (Shoulder stand)', 'hold', 2.5,
    ['Lie on the back, shoulders on a folded blanket, head on the mat.'],
    ['Lift the legs and hips, supporting the back with the hands.', 'Legs straight up, weight on the shoulders, not the neck.', 'Come down slowly.'],
    ['Turning the head while up.', 'Doing it with neck problems, high blood pressure, or during a period.'], false],
  ['halasana', 'Halasana (Plough pose)', 'hold', 2.5,
    ['From shoulder stand, or lying on the back.'],
    ['Lower the feet overhead toward the floor behind you.', 'Support the back or clasp the hands on the mat.', 'Roll down slowly.'],
    ['Any neck strain: stop.', 'Doing it with neck or back injuries.'], false],
  ['matsyasana', 'Matsyasana (Fish pose)', 'hold', 2.5,
    ['Lie on the back, legs straight; hands under the hips, palms down.'],
    ['Press the forearms down and lift the chest.', 'Lightly rest the crown of the head on the mat (little weight on it).', 'A counter-pose to shoulder stand.'],
    ['Putting body weight onto the head.'], false],
  ['viparita-karani', 'Viparita Karani (Legs up the wall)', 'hold', 1.3,
    ['Sit side-on to a wall, then swing the legs up it as you lie back.'],
    ['Hips close to the wall, arms relaxed.', 'Stay and breathe for a few minutes.'],
    ['Staying if the legs tingle: bend the knees.'], false],
  ['shavasana', 'Shavasana (Corpse pose)', 'hold', 1.3,
    ['Lie on the back, legs a little apart, arms by the sides, palms up.'],
    ['Close the eyes and let the whole body go heavy.', 'Breathe naturally; usually at the end of practice.'],
    ['Skipping it.'], false],
];

const PRANAYAMA: Pose[] = [
  ['anulom-vilom', 'Anulom Vilom (Nadi Shodhana)', 'time', 2.0,
    ['Sit tall in Sukhasana or on a chair; left hand on the knee.'],
    ['Close the right nostril with the right thumb; breathe in through the left.', 'Close the left with the ring finger; breathe out through the right. In through the right, out through the left: one round.', 'Keep the breath slow and even.'],
    ['Forcing or holding the breath.', 'Pressing hard on the nose.'], false],
  ['kapalbhati', 'Kapalbhati (Skull-shining breath)', 'time', 2.0,
    ['Sit tall, hands on the knees.'],
    ['Short, forceful exhales through the nose by snapping the belly in; let the inhale happen by itself.', 'Start with rounds of 20–30 breaths and rest between.'],
    ['Doing it on a full stomach, when pregnant, or with high blood pressure or heart problems.', 'Feeling dizzy: stop and breathe normally.'], false],
  ['bhastrika', 'Bhastrika (Bellows breath)', 'time', 2.0,
    ['Sit tall, hands on the knees.'],
    ['Breathe in and out forcefully through the nose, both equally strong, using the chest and belly.', 'Short rounds, then rest with normal breathing.'],
    ['Same cautions as Kapalbhati.', 'Carrying on through dizziness.'], false],
  ['bhramari', 'Bhramari (Humming bee breath)', 'time', 1.3,
    ['Sit tall; close the ears gently with the thumbs, fingers over the eyes.'],
    ['Breathe in through the nose; hum like a bee as you breathe out slowly.', 'Feel the vibration in the head.'],
    ['Pressing on the ears or eyes.'], false],
  ['ujjayi', 'Ujjayi (Victorious breath)', 'time', 1.3,
    ['Sit tall, or use it through a practice.'],
    ['Gently narrow the back of the throat so the breath sounds like soft waves.', 'Breathe in and out through the nose, long and even.'],
    ['Straining the throat.'], false],
  ['sheetali', 'Sheetali (Cooling breath)', 'time', 1.3,
    ['Sit tall.'],
    ['Roll the tongue into a tube (or breathe through the teeth: Sheetkari).', 'Breathe in through the tongue, close the mouth, breathe out through the nose.'],
    ['Doing it in the cold or with a cold.'], false],
  ['udgeeth', 'Udgeeth (Om chanting)', 'time', 1.3,
    ['Sit tall, eyes closed.'],
    ['Breathe in deeply; chant a long “Om” on the out-breath.', 'Repeat, letting the sound fade into silence.'],
    ['Rushing the breath in.'], false],
  ['dhyana', 'Dhyana (Meditation)', 'time', 1.3,
    ['Sit comfortably with the spine upright, eyes closed.'],
    ['Rest attention on the breath (or a word or sound).', 'When the mind wanders, notice and come back.'],
    ['Judging yourself for wandering.'], false],
];

const toEx = (group: string) => ([id, name, yoga, met, setup, exec, avoid, art]: Pose): Exercise => ({
  id, name, group, equip: 'Mat', weightType: 'bodyweight', kind: 'yoga', yoga, met: [met, met, met], setup, exec, avoid, ...(art === false ? { art } : {}),
});
export const YOGA: readonly Exercise[] = [...ASANAS.map(toEx('Yoga')), ...PRANAYAMA.map(toEx('Pranayama'))];
